# Generated by Django 3.1.7 on 2021-03-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_read', models.FileField(upload_to='')),
            ],
        ),
    ]
