# Generated by Django 3.1.7 on 2021-03-23 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0003_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Text',
        ),
    ]
